[package]
name = "throughtheterminal"
version = "0.2.0"
edition = "2021"

[package.metadata.bundle]
name = "throughtheterminal"
identifier = "com.ostromia.throughtheterminal"

[dependencies]
tao = "0.31.1"
toml = "0.8.19"
url = "2.5.4"
